import 'package:get/get.dart';

class AllSongsViewModel extends GetxController {
  final allList = [
    {
      "id": "csaEsVWV",
      "name": "Top list",
      "type": "",
      "album": "Rockstar",
      "year": "2011",
      "releaseDate": null,
      "duration": "473",
      "label": "",
      "artists": "10 songs[00:42:33]",
      "artistsId": "456269, 455926, 455124",
      "featuredArtists": "",
      "featuredArtistsId": "",
      "explicitContent": 0,
      "playCount": "32891706",
      "language": "hindi",
      "hasLyrics": "true",
      "url": "https://www.jiosaavn.com/song/kun-faaya-kun/ExsKdAdmYGU",
      "copyright": "©  2011 ",
      "image": "assets/img/pl1.png",
      "downloadUrl": "https://aac.saavncdn.com/274/aee250c500588f117ae5343688e12b42_160.mp4"
    },
    {
      "id": "1beIJP9H",
      "name": "Download music",
      "type": "",
      "album": "Kun faya Kun",
      "year": "2022",
      "releaseDate": null,
      "duration": "186",
      "label": "Prime Digital Arena",
      "artists": "75 songs[05:17:54]",
      "artistsId": "11294502",
      "featuredArtists": "",
      "featuredArtistsId": "",
      "explicitContent": 0,
      "playCount": "7777",
      "language": "urdu",
      "hasLyrics": "false",
      "url": "https://www.jiosaavn.com/song/kun-faya-kun/QQoOeD5gDns",
      "copyright": "(P) 2022 Prime Digital Arena",
      "image": "assets/img/pl2.png",
      "downloadUrl": "https://aac.saavncdn.com/237/35bc86c94065ebfba7f43dd0f0ed7f6c_160.mp4"
    },
    {
      "id": "-Rb5lPKJ",
      "name": "Pop music",
      "type": "",
      "album": "Kun Faya Kun",
      "year": "2019",
      "releaseDate": null,
      "duration": "284",
      "label": "PT Artha Musik Produksi",
      "artists": "101 songs[10:35:46]",
      "artistsId": "3084476",
      "featuredArtists": "",
      "featuredArtistsId": "",
      "explicitContent": 0,
      "playCount": "15803",
      "language": "indonesian",
      "hasLyrics": "false",
      "url": "https://www.jiosaavn.com/song/kun-faya-kun/XToJBBhgfHk",
      "copyright": "(P) 2019 Artha Music Production",
      "image": "assets/img/pl3.png",
      "downloadUrl": "https://aac.saavncdn.com/107/6b6a254924bc31176e65ffd0d71a17e5_160.mp4"
    },
    {
      "id": "brqxXg-c",
      "name": "Ballad music",
      "type": "",
      "album": "Kun Faya Kun",
      "year": "2023",
      "releaseDate": null,
      "duration": "255",
      "label": "Prime Digital Arena",
      "artists": "10 songs[00:42:33]",
      "artistsId": "10209176",
      "featuredArtists": "",
      "featuredArtistsId": "",
      "explicitContent": 0,
      "playCount": "160",
      "language": "urdu",
      "hasLyrics": "false",
      "url": "https://www.jiosaavn.com/song/kun-faya-kun/EhoaSSxXGlA",
      "copyright": "(P) 2023 Prime Digital Arena",
      "image": "assets/img/pl4.png",
      "downloadUrl": "https://aac.saavncdn.com/259/e4af4e445d24aa36e1be6b0f7fe28dfc_160.mp4"
    },
    {
      "id": "brqxXg-c",
      "name": "Ringtone music",
      "type": "",
      "album": "Kun Faya Kun",
      "year": "2023",
      "releaseDate": null,
      "duration": "255",
      "label": "Prime Digital Arena",
      "artists": "25 songs[01:36:29]",
      "artistsId": "10209176",
      "featuredArtists": "",
      "featuredArtistsId": "",
      "explicitContent": 0,
      "playCount": "160",
      "language": "urdu",
      "hasLyrics": "false",
      "url": "https://www.jiosaavn.com/song/kun-faya-kun/EhoaSSxXGlA",
      "copyright": "(P) 2023 Prime Digital Arena",
      "image": "assets/img/pl5.png",
      "downloadUrl": "https://aac.saavncdn.com/259/e4af4e445d24aa36e1be6b0f7fe28dfc_160.mp4"
    },
    {
      "id": "brqxXg-c",
      "name": "Love songs",
      "type": "",
      "album": "Kun Faya Kun",
      "year": "2023",
      "releaseDate": null,
      "duration": "255",
      "label": "Prime Digital Arena",
      "artists": "67 songs[04:21:06]",
      "artistsId": "10209176",
      "featuredArtists": "",
      "featuredArtistsId": "",
      "explicitContent": 0,
      "playCount": "160",
      "language": "urdu",
      "hasLyrics": "false",
      "url": "https://www.jiosaavn.com/song/kun-faya-kun/EhoaSSxXGlA",
      "copyright": "(P) 2023 Prime Digital Arena",
      "image": "assets/img/pl6.png",
      "downloadUrl": "https://aac.saavncdn.com/259/e4af4e445d24aa36e1be6b0f7fe28dfc_160.mp4"
    },
    {
      "id": "brqxXg-c",
      "name": "Funny song",
      "type": "",
      "album": "Kun Faya Kun",
      "year": "2023",
      "releaseDate": null,
      "duration": "255",
      "label": "Prime Digital Arena",
      "artists": "10 songs[00:42:33]",
      "artistsId": "10209176",
      "featuredArtists": "",
      "featuredArtistsId": "",
      "explicitContent": 0,
      "playCount": "160",
      "language": "urdu",
      "hasLyrics": "false",
      "url": "https://www.jiosaavn.com/song/kun-faya-kun/EhoaSSxXGlA",
      "copyright": "(P) 2023 Prime Digital Arena",
      "image": "assets/img/pl7.png",
      "downloadUrl": "https://aac.saavncdn.com/259/e4af4e445d24aa36e1be6b0f7fe28dfc_160.mp4"
    },
    {
      "id": "brqxXg-c",
      "name": "Soundtrack",
      "type": "",
      "album": "Kun Faya Kun",
      "year": "2023",
      "releaseDate": null,
      "duration": "255",
      "label": "Prime Digital Arena",
      "artists": "15 songs[1:20:32]",
      "artistsId": "10209176",
      "featuredArtists": "",
      "featuredArtistsId": "",
      "explicitContent": 0,
      "playCount": "160",
      "language": "urdu",
      "hasLyrics": "false",
      "url": "https://www.jiosaavn.com/song/kun-faya-kun/EhoaSSxXGlA",
      "copyright": "(P) 2023 Prime Digital Arena",
      "image": "assets/img/pl8.png",
      "downloadUrl": "https://aac.saavncdn.com/259/e4af4e445d24aa36e1be6b0f7fe28dfc_160.mp4"
    },
    // Các mục khác cũng cập nhật theo cách tương tự...
  ].obs;
}
